"""initial schema

Revision ID: 4c7ccbc3bff7
Revises: 
Create Date: 2026-03-01 07:29:36.999881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c7ccbc3bff7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scraper', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='web_scrapers'
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('scraper', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='run_status', schema='web_scrapers'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('events_total', sa.Integer(), nullable=False),
    sa.Column('events_new', sa.Integer(), nullable=False),
    sa.Column('events_ingested', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['web_scrapers.scrape_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='web_scrapers'
    )
    op.create_index('idx_scrape_runs_started_at', 'scrape_runs', ['started_at'], unique=False, schema='web_scrapers')
    op.create_table('signal_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['web_scrapers.scrape_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    schema='web_scrapers'
    )
    op.create_index('idx_signal_events_created_at', 'signal_events', ['created_at'], unique=False, schema='web_scrapers')
    op.create_index('idx_signal_events_scraped_at', 'signal_events', ['scraped_at'], unique=False, schema='web_scrapers')
    op.create_index('idx_signal_events_source', 'signal_events', ['source'], unique=False, schema='web_scrapers')
    op.create_index('idx_signal_events_source_type', 'signal_events', ['source', 'event_type'], unique=False, schema='web_scrapers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signal_events_source_type', table_name='signal_events', schema='web_scrapers')
    op.drop_index('idx_signal_events_source', table_name='signal_events', schema='web_scrapers')
    op.drop_index('idx_signal_events_scraped_at', table_name='signal_events', schema='web_scrapers')
    op.drop_index('idx_signal_events_created_at', table_name='signal_events', schema='web_scrapers')
    op.drop_table('signal_events', schema='web_scrapers')
    op.drop_index('idx_scrape_runs_started_at', table_name='scrape_runs', schema='web_scrapers')
    op.drop_table('scrape_runs', schema='web_scrapers')
    op.drop_table('scrape_jobs', schema='web_scrapers')
    # ### end Alembic commands ###
